core_shop_payment:
    pimcore_admin:
        js:
            powerpay: /bundles/powerpay/pimcore/js/powerpay.js

core_shop_workflow:
    state_machine:
        coreshop_payment:
            callbacks:
                before:
                    confirm_powerpay_payment:
                        on: ['complete']
                        do: ['@CoreShop\Payum\PowerpayBundle\Event\ConfirmEvent', 'confirmByPayment']
                        args: ['object']
                    cancel_powerpay_payment:
                        on: ['cancel']
                        do: ['@CoreShop\Payum\PowerpayBundle\Event\CancelEvent', 'cancel']
                        args: ['object']
                    refund_powerpay_payment:
                        on: ['refund']
                        do: ['@CoreShop\Payum\PowerpayBundle\Event\RefundEvent', 'refund']
                        args: ['object']
        coreshop_order_shipment:
            callbacks:
                after:
                    confirm_powerpay_payment:
                        on: ['ship']
                        do: ['@CoreShop\Payum\PowerpayBundle\Event\ConfirmEvent', 'confirmByOrder']
                        args: ['object']