services:

    CoreShop\Payum\PowerpayBundle\Extension\CustomerTransformerExtension:
        public: true
        tags:
            - { name: payum.extension, alias: powerpay_customer_transformer_extension, factory: powerpay, gateway: powerpay, prepend: false }

    CoreShop\Payum\PowerpayBundle\Extension\ConfirmPaymentExtension:
        public: true
        arguments:
            - '@coreshop.repository.payment'
            - '@coreshop.workflow.order_history_logger'
        tags:
            - { name: payum.extension, alias: powerpay_confirm_extension, factory: powerpay, gateway: powerpay, prepend: false }

    CoreShop\Payum\PowerpayBundle\Extension\CancelPaymentExtension:
        public: true
        arguments:
            - '@coreshop.repository.payment'
            - '@coreshop.workflow.order_history_logger'
        tags:
            - { name: payum.extension, alias: powerpay_cancel_extension, factory: powerpay, gateway: powerpay, prepend: false }

    CoreShop\Payum\PowerpayBundle\Extension\RefundPaymentExtension:
        public: true
        arguments:
            - '@coreshop.repository.payment'
            - '@coreshop.workflow.order_history_logger'
        tags:
            - { name: payum.extension, alias: powerpay_refund_extension, factory: powerpay, gateway: powerpay, prepend: false }

    CoreShop\Payum\PowerpayBundle\Extension\FailedPaymentExtension:
        public: true
        arguments:
            - '@pimcore.translator'
        tags:
            - { name: payum.extension, alias: powerpay_failed_extension, factory: powerpay, gateway: powerpay, prepend: false }

    CoreShop\Payum\PowerpayBundle\Form\Payment\PowerpaySettingsType:
        tags:
            - { name: coreshop.payment.form.settings, payum-factory: powerpay }
            - { name: form.type }

    CoreShop\Payum\PowerpayBundle\Form\Payment\PowerpayType:
        tags:
            - { name: coreshop.gateway_configuration_type, type: powerpay }
            - { name: form.type }

    CoreShop\Payum\PowerpayBundle\Event\ConfirmEvent:
        public: true
        arguments:
            - '@payum'
            - '@coreshop.repository.payment'

    CoreShop\Payum\PowerpayBundle\Event\CancelEvent:
        public: true
        arguments:
            - '@payum'

    CoreShop\Payum\PowerpayBundle\Event\RefundEvent:
        public: true
        arguments:
            - '@payum'

    payum.powerpay_gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [DachcomDigital\Payum\Powerpay\PowerpayGatewayFactory]
        tags:
            - {name: payum.gateway_factory_builder, factory: powerpay }
